name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      DB_URI: ${{ secrets.DB_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
      
    steps:
    - name: Debug env presence
      run: |
        echo "::add-mask::$DB_URI"  # keep the value hidden
        echo "DB_URI length: ${#DB_URI}"
        echo "REFRESH_SECRET_KEY set? $([ -n \"$REFRESH_SECRET_KEY\" ] && echo yes || echo no)"

    - name: Create .env file
      run: cd /home/ubuntu/perfect/actions-runner/_work/perfect-api/perfect-api
    - run: |
       echo "DB_URI=${{ secrets.DB_URI }}" >> .env
       echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
       echo "REFRESH_SECRET_KEY=${{ secrets.REFRESH_SECRET_KEY }}" >> .env

    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm dedupe
    - run: npm run build --if-present

    # - name: Change Directory
    #   run: cd /home/frandendstartawsil/actions-runner/_work/frontend/frontend
    # - run: pm2 reload 0 
