name: NestJS Deploy CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DB_URI: ${{ secrets.DB_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deduplicate dependencies
        run: npm dedupe

      - name: Build the project
        run: npm run build

      - name: Debug DB_URI
        run: | 
          echo "Mongo prefix: ${DB_URI:0:10}"  # should print mongodb://

      - name: Start NestJS App
        run: npm run start:prod
        env:
          DB_URI: ${{ secrets.DB_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}